### ISSUE TITLE
Manifest EN version

### ISSUE THREAD

**Issue by rozhok** [ItGuildUa/core#12]
Зробити англійську версію маніфесту

**Comment by egopher** [comment]
Принято. Осталось найти волонтеров.

**Comment by 1petr0v** [comment]
ACK, picking it up.

**Comment by 1petr0v** [comment]
Done. Proofread would be a good option. Also, text was checked with Grammarly.

**Comment by 1petr0v** [comment]
As per the known issue in the manifesto - the Screen Actors Guild (SAG) _does not grant_ the Oscar award - I was not able to find a good showcase regarding SAG, even though the fact that it's a powerful and respected organization is beyond doubts.

As an alternative, I can propose the following alternatives:
- Option 1. Change in the manifesto _the Screen Actors Guild_ -> _Academy of Motion Picture Arts and Sciences_ that is another powerful professional organization and it actually awards Oscar.
- Option 2. Pick another showcase from one of the success stories listed [here](https://aflcio.org/about-us/history).

**Comment by 1petr0v** [comment]
I decided to proceed with option 1 as a temporary fix for now.
