### ISSUE TITLE
Вычитка контрактов

### ISSUE THREAD

**Issue by i-zu** [ItGuildUa/core#25]
Вычитка контрактов - это то, за чем лично мне было бы интересно обратиться к гильдии. Я готов оплатить услуги юриста, но было бы хорошо, чтобы гильдия могла его предоставить без необходимости тратить время на самостоятельные поиски.

**Comment by rozhok** [comment]
Такий проект обов'язково буде, це в першій черзі.

**Comment by egopher** [comment]
Done. Звертайтесь на канал - юридична допомога у дискорді.
