### ISSUE TITLE
Лист депутатам щодо 4303

### ISSUE THREAD

**Issue by rozhok** [ItGuildUa/core#41]
- [x] Написати лист депутатам
- [x] Знайти прийомні емейли всіх депутатів
- [x] Розіслати в електронному вигляді
- [ ] Розіслати в паперовому вигляді

**Comment by rozhok** [comment]
@alex-raiev написав драфт: https://drive.google.com/file/d/1t91PjS0soTpGKjszgPmGe0Z5g0QwpJcA/view?usp=sharing

**Comment by rozhok** [comment]
Зібрав емейли депутатів

**Comment by alex-raiev** [comment]
Чорновик окремого листа до Ар'єва:
https://drive.google.com/file/d/1kjM1DQn5lN4aspZjS8HP2LQ5tz2HZNcD/view?usp=sharing

**Comment by dmitryls** [comment]
> Чорновик окремого листа до Ар'єва:
> https://drive.google.com/file/d/1kjM1DQn5lN4aspZjS8HP2LQ5tz2HZNcD/view?usp=sharing

исправил несколько орфографических ошибок

**Comment by mikek** [comment]
Чати, але все ще не дуже зрозуміло, як, коли і що розсилати можуть окремі люди.

 - Який саме темплейт останній?
 - Що змінюється в цьому плані, якщо тепер 5376 перший?
 - Чи є сенс на email окремо писати їм всім від кожного з нас?
 - Паперові є сенс тількі «свому дпутату» надсилати?

**Comment by dodikk** [comment]
@mikek спробую відповісти від себе (не від гільдії офіційно)

> Який саме темплейт останній?

Я слав email із текстом (`plain text`, не `html`) звідси. Тут більше виправлених помилок (на мій погляд, смак та обізнаність в українському правописі).
https://drive.google.com/file/d/1KgBgV2qBEUIUVSBhXdeGNjGgQnsnkTY2/view?usp=sharing

прибравши текст щодо "також член комітету з цифрової трансформації"
"шапку паперового документу" я зберіг (згідно з рекомендаціями від @rozhok ) відповідно "засвітивши" своє ім'я, адресу та телефон (але ж це уряд, вони і так десь мають "досьє" на кожного з нас)
та й пошту взяв `@ukr.net` - аби більш "офіційно" виглядало.

> Що змінюється в цьому плані, якщо тепер 5376 перший?

особисто я не знаю. напевне, нічого. бо готувати нові листи може бути марно. краще вже `4303` "добивати"

> Чи є сенс на email окремо писати їм всім від кожного з нас?

`цілковито має`. адже від одного `email` можна легко відмахнутись. а коли увесь `inbox` завалено такими листами - це буде сприйматися значно серйозніше.


> Паперові є сенс тількі «свому дпутату» надсилати?

Має сенс на усіх. Але спершу зроби хоча б emails. Без автоматизації це досить багато рутини, та й автоматизацію треба накодити та протестувати (перш ніж на реальні депутатьскі адреси запускати)
