### ISSUE TITLE
Правила поведінки у чатах

### ISSUE THREAD

**Issue by rozhok** [ItGuildUa/core#46]
Потрібно взяти існуючий CoC та адаптувати під нас. Непоганий варіант також є у vas3k.club, можна взяти і звідти.

**Comment by egopher** [comment]
Предлагаю взять https://vas3k.club/docs/about/ за основу.

**Comment by alex-raiev** [comment]
Вітаю тебе,  [username] в чаті|каналі Гільдії
Саме тут ти маєш змогу:
1. Дізнатися про новини Гільдії та обговорити їх.
2. Поспілкуватися щодо програми Гільдії та її розвитку.
3. Знайти гільдійців у своєму місті чи приєднатися до осередку.
4. Задати питання лідерам організації та отримати відповідь.
Є декілька простих правил спілкування, які зроблять перебування тут зручніше.
Флуд - заборонено. Це - суто офіційний майданчик, де обговорюється саме діяльність Гільдії, а не загальні новини чи інші політичні діячі. 
Беззмістовні, рекламні та дублюючі повідомлення будуть видалятися з попередженням. Після повторного порушення - readonly на день/тиждень.
Перехід на особистості - заборонено. За порушення - readonly на тиждень без попереджень.
Мат – дозволено, але в обмеженій кількості та тільки там де не можна висловити думку іншими словами.
Відкрите пропагування насилля, харасменту в будь якому прояві буде видалятись із попередженням. 
Реклама політичних партій буде видалятись з попередженням. Обговорення політичних сил може здійснюватись тільки в сені подій чи акцій напряму пов’язаних із цілями та діяльністю Гільдії. Такі повідомлення будуть видалятись із попередженням. Після повторного порушення – readonly на тиждень.
За можливості — викладайте інформацію стисло. Ось рекомендації:
1)  Якщо бажаєте обсудити новину чи висловити подяку Гільдії за якусь подію — зробіть це одним окремим повідомленням. Якщо подяк вже багато — краще не робіть, чи зробіть це в особистих повідомленнях.
2)  Якщо вам потрібно прояснити позицію Гільдії з якогось питання — зверніться до адміністрації, чи викладіть свої питання в одному повідомленні. Якщо після відповіді залишаться додаткові питання, які потребують довгої розмови — перейдіть до особистих повідомлень з керівником(ами) Гільдії. 
3)  Не відповідайте на запитання, які адресовані не вам. Чи робіть це в приватних повідомленнях.
4)  Почуття гумору вітається у межах розумного та відповідно до теми обговорення.
Обов'язково почитай інформаційний листок для новачків за ось цим посиланням: https:// ….

**Comment by egopher** [comment]
Done - https://www.itguild.org.ua/coc/
